config: {}
dwh:
  outputs:
    dwh:
      driver: native
      port: 9000
      host: clickhouse
      password: default
      schema: prod
      threads: 1
      type: clickhouse
      send_receive_timeout: 3600
      user: default
  target: dwh
