config: {}
dwh:
  outputs:
    bronze:
      dataset: bronze_hiu_lh
      job_execution_timeout_seconds: 600
      job_retries: 1
      location: asia-southeast1
      method: oauth
      priority: interactive
      project: intelligent-data-lake-house
      threads: 1
      type: bigquery
  target: bronze
  outputs:
    silver:
      dataset: silver_hiu_lh
      job_execution_timeout_seconds: 600
      job_retries: 1
      location: asia-southeast1
      method: oauth
      priority: interactive
      project: intelligent-data-lake-house
      threads: 1
      type: bigquery
  outputs:
    gold:
      dataset: gold_hiu_lh
      job_execution_timeout_seconds: 600
      job_retries: 1
      location: asia-southeast1
      method: oauth
      priority: interactive
      project: intelligent-data-lake-house
      threads: 1
      type: bigquery
  target: gold
