config: {}
dwh:
  outputs:
    lumin:
      driver: native
      port: 9134
      host: localhost
      password: default
      schema: prod
      threads: 2
      type: clickhouse
      send_receive_timeout: 3600
      user: default
  target: dwh
